Account creation page and login page
KaruzG/chirp pull request #18
Opened 2024-01-30 12:15 UTC by JME469

Structure for the login and creation page, also added basic JavaScript validation for the creation page (/public/js/signup.js)
Disclaimer: This branch also contains the advances and changes on the feed page due to some github branch issues I had, it is now solved but just know this branch is being used to work on both Login/creation and feed. Let me know what you think!

2024-01-30 12:27 UTC, KaruzG requested changes
I think you unintencionally added commits from another feature (feed)

2024-01-30 12:27 UTC, KaruzG commented on public/pages/feed.html
This is a PR for the login not the feed

2024-01-30 19:32 UTC, JME469 reviewed
I already separated the unwanted commits (feed page changes) into another branch, also solved conflicts

2024-01-31 15:15 UTC, KaruzG approved these changes
Nice! 💥💥💥

2024-02-01 08:00 UTC, Rafval18 approved these changes
Good Job!

2024-02-01 08:04 UTC, merged